### PR TITLE
support non-project folders

### PR DESCRIPTION
**Pull request by toolboxen**
fixes https://github.com/renerocksai/sublime_zk/issues/11

now both project folders and non-project folders are supported by the plugin.

### CODE REVIEW

**Comment by renerocksai** [comment]
Oh, just noticed it. Can you tell me: What path do you get when there is no view with a path, ie a blank new file in a project-less window?

**Comment by toolboxen** [comment]
If there is just a folder but no open file the path is retrieved by `os.path.abspath(self.view.window().folders()[0])` does that answer your question?

**Comment by toolboxen** [comment]
If it's just an empty window with a blank new file of `untitled` i don't think there is a path available.

**Comment by toolboxen** [comment]
Yeah, there is no path for Sublime to work with if there is no open folder, no project folder, and a blank `untitled` file. There needs to be at least an open saved file, or an open folder in order to get a path.

**Comment by renerocksai** [comment]
OK so in the case `os.path.abspath(self.view.window().folders()[0])` where the window is just a new window, no project --> there is no path. The filename of a new note would then become the note ID + extension with no path. The OS would decide where to put it. Maybe the current working directory of the SublimeText executable... Isn't that a problem? 

When we support working project-less then people might just start with an empty window and press the `new note` key combination. It would be created at a seemingly random location...?

**Comment by renerocksai** [comment]
Just one more detail: `os.path.abspath(self.window.folders()[0])` creates: `IndexError: list index out of range` further showing that a new window has no path :(.

See my comments to the issue. Maybe we can solve it in a clean way.

Best
Rene

**Comment by renerocksai** [comment]
See the issue comments: I know how to fix the `new_zettel` command on an empty window: I just invoke `save_project_as` :). Thanks for your contributions! We're already way better than we were yesterday :+1:

**Comment by toolboxen** [comment]
Good solution and I was thinking along the same lines although I was just thinking of an error message, your solution is better... see my comments here: https://github.com/renerocksai/sublime_zk/issues/11#issuecomment-341866690 -- glad you got it handled so nicely,

**Pull request merged**
